services:
  firewall:
    init: true
    tty: true
    stdin_open: true

    image: fw_img
    platform: ${FW_PLATFORM}
    privileged: true
    container_name: ${FW_NAME}
    hostname: ${FW_NAME}
    sysctls: 
      - net.ipv4.ip_forward=1
    environment:
      USERNAME: ${FW_USER}
      PASSWD: ${FW_PASS}
    volumes:
      - fw-data:/home/${FW_NAME}
    build: 
      dockerfile: ./fw.Dockerfile
      args:
        UBUNTU_VER: ${FW_UBUNTU_VER}
      platforms: 
        - ${FW_PLATFORM}

    networks:
      int_network:
        ipv4_address: ${FW_INT_IPADDR}

      ext_network:
        ipv4_address: ${FW_EXT_IPADDR}

      internet: {}


  int_host:
    init: true
    tty: true
    stdin_open: true

    image: host_img
    cap_add:
      - NET_ADMIN
    container_name: ${INT_HOST_NAME}
    hostname: ${INT_HOST_NAME}
    environment:
      USERNAME: ${INT_HOST_NAME}
      PASSWD: ${FW_PASS}
      SUBNET: ${EXT_SUBNET}
      DEFAULT_GATEWAY: ${FW_INT_IPADDR}
    volumes:
      - int-host-data:/home/${INT_HOST_NAME}
    build: 
      dockerfile: ./host.Dockerfile
      args:
        USERNAME: ${INT_HOST_NAME}

    networks:
      int_network:
        ipv4_address: ${INT_HOST_IPADDR}


  ext_host:
    init: true
    tty: true
    stdin_open: true

    image: host_img
    cap_add:
      - NET_ADMIN
    container_name: ${EXT_HOST_NAME}
    hostname: ${EXT_HOST_NAME}
    environment:
      USERNAME: ${EXT_HOST_NAME}
      PASSWD: ${FW_PASS}
      SUBNET: ${INT_SUBNET}
      DEFAULT_GATEWAY: ${FW_EXT_IPADDR}
    volumes:
      - ext-host-data:/home/${EXT_HOST_NAME}
    build: 
      dockerfile: ./host.Dockerfile
      args:
        USERNAME: ${EXT_HOST_NAME}

    networks:
      ext_network:
        ipv4_address: ${EXT_HOST_IPADDR}


networks:
  internet: {} # connection to regular internet

  int_network:
    # internal: true
    driver: bridge
    driver_opts:
      com.docker.network.container_iface_prefix: internal
    ipam:
      config:
        - subnet: ${INT_SUBNET}

  ext_network:
    # internal: true
    driver: bridge
    driver_opts:
      com.docker.network.container_iface_prefix: external
    ipam:
      config:
        - subnet: ${EXT_SUBNET}

volumes:
  fw-data: {}
  int-host-data: {}
  ext-host-data: {}

